### ISSUE TITLE
xl-gutter-24 is not working

### ISSUE THREAD

**Issue by mahmut-gundogdu** [dnomak/flexiblegs-css#2]
i use chrome 55 on windows 10.  this is codepen
http://codepen.io/mgundogdu38/pen/woYWEL

**Comment by dnomak** [comment]
açıp kapatmışsın issue'yu ama çalışmasında bir sıkıntı yok bu verdiğin background renklerini col içerisinde yeni bir div açıp o şekilde eklemelisin gutterları padding ile verdiğimiz için bu şekilde bir kullanım yanlış oluyor.

**Comment by mahmut-gundogdu** [comment]
Evet önce resimden gutter in margin verdiğini düşündüm. Bir türlü resimler arası açılmayınca çalışmıyor dedim. 
![gutter](https://cloud.githubusercontent.com/assets/2217899/21175080/63028cfc-c1e9-11e6-8b6f-9ab7df94c752.png)
Bu örnekte görüntüyü yanlış yorumlamısım. ben arada renk farkı olunca margin gibi düşünmüştüm. Sonra dedim bir sorayım. Sonra bir ne yapıyormus kodu okuyayım dedim. o zaman padding verdiğini görünce issue kapattım.

**Comment by dnomak** [comment]
evet ama bu attığın görüntüde insanı yanıltıyor gerçekten onu çıkartan kodla örnekte yazdığım aynı değil kodda karmaşa olmasın diye örnek kod parçasına eklemedim ama doğru olmamış insanlar yanlış yönlenebilir bunu bir daha gözden geçireyim ben teşekkür ederim :)
