### ISSUE TITLE
Esnek kutuların kapsayıcı yüksekliğini almaması.

### ISSUE THREAD

**Issue by erkanunluturk** [dnomak/flexiblegs-css#3]
merhaba, bir projede iki kolon, kapsayıcının yüksekliğine eşitlenmesi gerekiyordu kutular `align-items: center` la ortalanmış diğer yandan `*-middle` boşa çıkmış oluyor. esnek kutuların varsayılan değeri `strech` [http://codepen.io/erkanunluturk/pen/xgdVRa?editors=1100](http://codepen.io/erkanunluturk/pen/xgdVRa?editors=1100) şöyle bi çözüm bularak `*-middle` yi kendim atayarak ortalanmasını sağladım. hem `*-middle` işe yaramış oldu hemde varsayılan değer olan `strech` e döndü. yani sonuç, bunun flexible.gs üzerinde olması güzel olurdu.

**Comment by dnomak** [comment]
gönderdiğin örnekte tam olarak nasıl bir değişiklik yaptın anlayamadım bir de middle kullanımıyla ilgili şu sayfayıda iletiyim görmemişsindir belki diye http://flexible.gs/learn/middle?method=css

**Comment by erkanunluturk** [comment]
gönderdiğim örnekte varsayılan `stretch` özelliğine döndürüp ortalamayı kendim atayarak yapmasını sağladım. demek istediğim flexiblegs' de `aligin-content` özelliği eksik, kolonlar yatay ve dikey olmak üzere herzaman ortadan başlıyor. [http://fatihhayrioglu.com/yenilenmis-flex-modulu/](http://fatihhayrioglu.com/yenilenmis-flex-modulu/). kapsayıcının yüksekliğine eşitlemem için stretch özelliği olmalı.

**Comment by erkanunluturk** [comment]
örnekte de `xl-middle` yi silip görebilirsiniz.

[http://codepen.io/erkanunluturk/pen/xgdVRa?editors=1100](http://codepen.io/erkanunluturk/pen/xgdVRa?editors=1100)

**Comment by erkanunluturk** [comment]
```css

*-stretch {
 align-content: stretch;
 align-items: stretch;
}

```

böyle bir özellik eklenebilir.

**Comment by erkanunluturk** [comment]
kusura bakmayın emin olamadım,
```css
*-stretch {
  align-items: stretch;
  align-content: stretch;
}
```
bu özellik benim sorunumu çözdü, eklenmesi güzel olur.

**Comment by dnomak** [comment]
tamamdır süpersin teşekkürler :)

**Comment by dnomak** [comment]
bununla ilgili şöyle bir issue daha vardı bunu kapatıyorum https://github.com/flexiblegs/flexiblegs-scss/issues/1 önümüzdeki günlerde gerekli güncellemeleri yapıcam.
